name: deploy-backend
on:
  push:
    paths:
      - 'museum-backend/**'
      - '.github/workflows/deploy-backend.yml'
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: ./museum-backend
          file: ./museum-backend/deploy/Dockerfile.prod
          push: true
          tags: |
            ghcr.io/${{ secrets.GHCR_USER }}/museum-backend:latest
            ghcr.io/${{ secrets.GHCR_USER }}/museum-backend:${{ github.sha }}

      - name: Deploy on VPS (pull & restart backend)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            set -e
            cd /srv/museum
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USER }}" --password-stdin || true
            docker compose pull backend
            docker compose up -d --remove-orphans backend
