// AUTO-GENERATED by design-system/build.ts — DO NOT EDIT

export const primaryScale = {
  '50': '#EAF2FF',
  '100': '#D8E8FF',
  '200': '#B0CFFF',
  '300': '#80B2FF',
  '400': '#5090FF',
  '500': '#2563EB',
  '600': '#1D4ED8',
  '700': '#1E40AF',
  '800': '#1E3A8A',
  '900': '#172554',
} as const;

export const accentScale = {
  '400': '#38BDF8',
  '500': '#0EA5E9',
  '600': '#0284C7',
} as const;

export const goldScale = {
  '400': '#D4A853',
  '500': '#C49A3C',
  '600': '#A67C2E',
} as const;

export const textColors = {
  primary: '#0F172A',
  secondary: '#334155',
  tertiary: '#475569',
  muted: '#94A3B8',
  placeholder: '#64748B',
} as const;

export const darkTextColors = {
  primary: '#F8FAFC',
  secondary: '#94A3B8',
  tertiary: '#7C8CA2',
  muted: '#64748B',
  placeholder: '#64748B',
} as const;

export const surfaceColors = {
  default: '#FFFFFF',
  elevated: '#F8FAFC',
  muted: '#F1F5F9',
} as const;

export const darkSurfaceColors = {
  default: '#0F172A',
  elevated: '#1E293B',
  muted: '#334155',
} as const;

export const statusColors = {
  error: { light: '#991B1B', dark: '#FCA5A5' },
  errorBg: { light: 'rgba(254,242,242,0.82)', dark: 'rgba(127,29,29,0.4)' },
  success: { light: '#166534', dark: '#86EFAC' },
  successBg: { light: 'rgba(220,252,231,0.78)', dark: 'rgba(34,197,94,0.15)' },
  danger: { light: '#DC2626', dark: '#EF4444' },
  warning: { light: '#92400E', dark: '#FCD34D' },
  warningBg: { light: 'rgba(254,243,199,0.78)', dark: 'rgba(245,158,11,0.15)' },
} as const;

export const fontSize = {
  xs: 12,
  sm: 14,
  base: 16,
  lg: 18,
  xl: 20,
  '2xl': 24,
  '3xl': 30,
  '4xl': 36,
} as const;

export const fontWeight = {
  regular: '400',
  medium: '500',
  semibold: '600',
  bold: '700',
} as const;

export const lineHeight = {
  tight: 1.1,
  snug: 1.25,
  normal: 1.5,
  relaxed: 1.625,
} as const;
