// AUTO-GENERATED by design-system/build.ts — DO NOT EDIT

export const primaryScale = {
  '50': '#EAF2FF',
  '100': '#D8E8FF',
  '200': '#B0CFFF',
  '300': '#80B2FF',
  '350': '#60A5FA',
  '400': '#5090FF',
  '500': '#2563EB',
  '600': '#1D4ED8',
  '700': '#1E40AF',
  '800': '#1E3A8A',
  '900': '#172554',
} as const;

export const accentScale = {
  '400': '#38BDF8',
  '500': '#0EA5E9',
  '600': '#0284C7',
} as const;

export const goldScale = {
  '400': '#D4A853',
  '500': '#C49A3C',
  '600': '#A67C2E',
} as const;

export const textColors = {
  primary: '#0F172A',
  secondary: '#334155',
  tertiary: '#475569',
  muted: '#94A3B8',
  placeholder: '#64748B',
} as const;

export const darkTextColors = {
  primary: '#F8FAFC',
  secondary: '#94A3B8',
  tertiary: '#7C8CA2',
  muted: '#64748B',
  placeholder: '#64748B',
} as const;

export const surfaceColors = {
  default: '#FFFFFF',
  elevated: '#F8FAFC',
  muted: '#F1F5F9',
} as const;

export const darkSurfaceColors = {
  default: '#0F172A',
  elevated: '#1E293B',
  muted: '#334155',
} as const;

export const statusColors = {
  error: { light: '#991B1B', dark: '#FCA5A5' },
  errorBg: { light: 'rgba(254,242,242,0.82)', dark: 'rgba(127,29,29,0.4)' },
  success: { light: '#166534', dark: '#86EFAC' },
  successBg: { light: 'rgba(220,252,231,0.78)', dark: 'rgba(34,197,94,0.15)' },
  danger: { light: '#DC2626', dark: '#EF4444' },
  warning: { light: '#92400E', dark: '#FCD34D' },
  warningBg: { light: 'rgba(254,243,199,0.78)', dark: 'rgba(245,158,11,0.15)' },
} as const;

export const fontSize = {
  '2xs': 9,
  'xs-': 10,
  xs: 12,
  'sm-': 13,
  sm: 14,
  'base-': 15,
  base: 16,
  'lg-': 17,
  lg: 18,
  xl: 20,
  '2xl': 24,
  '2xl+': 26,
  '3xl': 30,
  '4xl': 36,
  '5xl': 48,
} as const;

export const fontWeight = {
  regular: '400',
  medium: '500',
  semibold: '600',
  bold: '700',
} as const;

export const lineHeight = {
  tight: 1.1,
  snug: 1.25,
  normal: 1.5,
  relaxed: 1.625,
} as const;

export const lineHeightPx = {
  '18': 18,
  '19': 19,
  '21': 21,
  '22': 22,
} as const;

export const space = {
  '1': 4,
  '2': 8,
  '3': 12,
  '4': 16,
  '5': 20,
  '6': 24,
  '7': 28,
  '8': 32,
  '9': 36,
  '10': 40,
  '12': 48,
  '14': 56,
  '18': 72,
  '20': 80,
  '0.5': 2,
  '1.5': 6,
  '2.5': 10,
  '3.5': 14,
  '4.5': 18,
  '5.5': 22,
  '12.5': 50,
} as const;

export const radius = {
  xs: 4,
  sm: 6,
  md: 8,
  DEFAULT: 10,
  lg: 12,
  xl: 14,
  '2xl': 16,
  '3xl': 20,
  '4xl': 24,
  '5xl': 36,
  full: 999,
} as const;

export const gradientColors = {
  lightEnd: '#D5F0FF',
} as const;

// Component tokens — button primitive (Spec B / T33)
export const buttonTokens = {
  variants: {
    primary: {
      bg: '#2563EB',
      bgPressed: '#1D4ED8',
      bgDisabled: '#B0CFFF',
      border: 'transparent',
      text: '#FFFFFF',
    },
    secondary: {
      bg: 'transparent',
      bgPressed: '#EAF2FF',
      bgDisabled: 'transparent',
      border: '#2563EB',
      text: '#2563EB',
    },
    destructive: {
      bg: '#DC2626',
      bgPressed: '#B91C1C',
      bgDisabled: '#FCA5A5',
      border: 'transparent',
      text: '#FFFFFF',
    },
  },
  sizes: {
    sm: { paddingV: 8, paddingH: 12, fontSize: 13, radius: 8 },
    md: { paddingV: 12, paddingH: 16, fontSize: 15, radius: 10 },
    lg: { paddingV: 16, paddingH: 20, fontSize: 17, radius: 12 },
  },
} as const;

export type ButtonVariant = keyof typeof buttonTokens.variants;
export type ButtonSize = keyof typeof buttonTokens.sizes;

// Component tokens — empty-state primitive (Spec B / T35)
export const emptyStateTokens = {
  variants: {
    chat: {
      iconName: 'chatbubble-ellipses-outline',
      iconColor: '#2563EB',
      iconBg: '#EAF2FF',
    },
    museums: {
      iconName: 'business-outline',
      iconColor: '#0EA5E9',
      iconBg: '#E0F2FE',
    },
    reviews: {
      iconName: 'star-outline',
      iconColor: '#D4A853',
      iconBg: '#FEF9EC',
    },
    dailyArt: {
      iconName: 'image-outline',
      iconColor: '#7C3AED',
      iconBg: '#EDE9FE',
    },
    conversations: {
      iconName: 'albums-outline',
      iconColor: '#0EA5E9',
      iconBg: '#E0F2FE',
    },
  },
  layout: {
    padding: 32,
    gap: 16,
    iconSize: 80,
    titleSize: 18,
    descriptionSize: 14,
  },
} as const;

export type EmptyStateVariant = keyof typeof emptyStateTokens.variants;
