// AUTO-GENERATED by design-system/build.ts — DO NOT EDIT

/**
 * Converts a hex color to rgba with the given alpha.
 * Works with 3-char (#fff), 6-char (#ffffff), and 8-char (#ffffffaa) hex.
 */
export function withOpacity(hex: string, alpha: number): string {
  const clean = hex.replace('#', '');
  let r: number, g: number, b: number;
  if (clean.length === 3) {
    r = parseInt(clean[0] + clean[0], 16);
    g = parseInt(clean[1] + clean[1], 16);
    b = parseInt(clean[2] + clean[2], 16);
  } else {
    r = parseInt(clean.slice(0, 2), 16);
    g = parseInt(clean.slice(2, 4), 16);
    b = parseInt(clean.slice(4, 6), 16);
  }
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

export const functional = {
  glassBorder: 'rgba(255, 255, 255, 0.58)',
  glassBackground: 'rgba(255, 255, 255, 0.44)',
  cardBackground: 'rgba(255, 255, 255, 0.66)',
  cardBorder: 'rgba(148, 163, 184, 0.42)',
  inputBackground: 'rgba(255, 255, 255, 0.7)',
  inputBorder: 'rgba(148, 163, 184, 0.45)',
  surface: 'rgba(255, 255, 255, 0.64)',
  overlay: 'rgba(255, 255, 255, 0.70)',
  separator: 'rgba(148, 163, 184, 0.35)',
  userBubble: 'rgba(30, 64, 175, 0.88)',
  userBubbleBorder: 'rgba(191, 219, 254, 0.6)',
  assistantBubble: 'rgba(255, 255, 255, 0.72)',
  assistantBubbleBorder: 'rgba(148, 163, 184, 0.22)',
  primaryTint: 'rgba(30, 64, 175, 0.06)',
  primaryBorderSubtle: 'rgba(30, 64, 175, 0.2)',
  timestamp: 'rgba(100, 116, 139, 0.92)',
  modalOverlay: 'rgba(0, 0, 0, 0.4)',
  overlayLight: 'rgba(0, 0, 0, 0.15)',
  overlayMedium: 'rgba(0, 0, 0, 0.6)',
  overlayHeavy: 'rgba(0, 0, 0, 0.95)',
  shadowSubtle: 'rgba(0, 0, 0, 0.08)',
  shadowMedium: 'rgba(0, 0, 0, 0.15)',
  primaryGlow: 'rgba(37, 99, 235, 0.08)',
  primaryGlowMedium: 'rgba(37, 99, 235, 0.12)',
  darkGlassBorder: 'rgba(255, 255, 255, 0.12)',
  darkGlassBackground: 'rgba(30, 41, 59, 0.72)',
  darkCardBackground: 'rgba(30, 41, 59, 0.66)',
  darkCardBorder: 'rgba(148, 163, 184, 0.18)',
  darkInputBackground: 'rgba(30, 41, 59, 0.7)',
  darkInputBorder: 'rgba(148, 163, 184, 0.25)',
  darkSurface: 'rgba(30, 41, 59, 0.64)',
  darkOverlay: 'rgba(15, 23, 42, 0.70)',
  darkSeparator: 'rgba(148, 163, 184, 0.25)',
  darkUserBubble: 'rgba(30, 64, 175, 0.92)',
  darkUserBubbleBorder: 'rgba(96, 165, 250, 0.4)',
  darkAssistantBubble: 'rgba(30, 41, 59, 0.72)',
  darkAssistantBubbleBorder: 'rgba(148, 163, 184, 0.18)',
  darkPrimaryTint: 'rgba(96, 165, 250, 0.1)',
  darkPrimaryBorderSubtle: 'rgba(96, 165, 250, 0.2)',
  darkTimestamp: 'rgba(148, 163, 184, 0.72)',
  darkModalOverlay: 'rgba(0, 0, 0, 0.6)',
  darkShadowColor: '#000000',
  webGlass: 'rgba(255, 255, 255, 0.55)',
  webGlassBorder: 'rgba(255, 255, 255, 0.35)',
  webGlassInset: 'rgba(255, 255, 255, 0.6)',
  webGlassHeavy: 'rgba(255, 255, 255, 0.72)',
  webGlassCard: 'rgba(255, 255, 255, 0.5)',
  webGlassCardHover: 'rgba(255, 255, 255, 0.65)',
  webLiquidGlass: 'rgba(255, 255, 255, 0.12)',
  webLiquidGlassBorder: 'rgba(255, 255, 255, 0.18)',
  webLiquidGlassHeavy: 'rgba(255, 255, 255, 0.18)',
  webLiquidGlassCard: 'rgba(255, 255, 255, 0.45)',
  webLiquidGlassCardHover: 'rgba(255, 255, 255, 0.6)',
  webSpecularHighlight: 'rgba(31, 38, 135, 0.15)',
  webSpecularHeavy: 'rgba(31, 38, 135, 0.18)',
} as const;
