// AUTO-GENERATED by design-system/build.ts — DO NOT EDIT

// Unified design system barrel — import everything from here
// Usage: import { space, fontSize, semantic, functional, withOpacity } from '@/shared/ui/tokens';

// Layer 1 — Primitives
export {
  primaryScale,
  accentScale,
  goldScale,
  textColors,
  darkTextColors,
  surfaceColors,
  darkSurfaceColors,
  statusColors,
  fontSize,
  fontWeight,
  lineHeight,
  lineHeightPx,
  space,
  radius,
  gradientColors,
} from './tokens.generated';

// Layer 2 — Functional (RGBA + utility)
export { functional, withOpacity } from './tokens.functional';

// Layer 3 — Semantic (component tokens)
export { semantic } from './tokens.semantic';
