import type { Dictionary } from '@/lib/i18n';

/** Shared mock admin dictionary for all admin page tests. */
export const mockAdminDict: Dictionary['admin'] = {
  dashboard: 'Dashboard',
  users: 'Users',
  auditLogs: 'Audit Logs',
  reports: 'Reports',
  analytics: 'Analytics',
  tickets: 'Tickets',
  supportAdmin: 'Support',
  reviewsAdmin: 'Reviews',
  nps: 'NPS',
  accessDenied: 'Access Denied',
  goToHomepage: 'Go to Homepage',
  login: {
    title: 'Admin Login',
    emailPlaceholder: 'Email',
    passwordPlaceholder: 'Password',
    submit: 'Sign In',
    error: 'Invalid credentials',
    googleButton: 'Continue with Google',
    divider: 'or',
    oauthError: 'Google sign-in failed.',
    mfaTitle: 'Two-factor authentication',
    mfaInstructions: 'Enter the 6-digit code from your authenticator app.',
    mfaCodeLabel: 'Authentication code',
    mfaCodePlaceholder: '123456',
    mfaSubmit: 'Verify and sign in',
    mfaUseRecovery: 'Use a recovery code instead',
    mfaRecoveryLabel: 'Recovery code',
    mfaRecoveryPlaceholder: 'Recovery code',
    mfaRecoverySubmit: 'Sign in with recovery code',
    mfaRecoveryContinue: 'Continue to admin',
    mfaBackToCode: 'Back to authenticator code',
    mfaErrorInvalid: 'That code is incorrect. Please try again.',
    mfaErrorRateLimited: 'Too many attempts. Please wait a moment before trying again.',
    mfaErrorExpired: 'Your session expired. Please sign in again.',
    mfaRecoveryRemaining: '{count} recovery codes remaining.',
  },
  common: {
    date: 'Date',
    status: 'Status',
    priority: 'Priority',
    actions: 'Actions',
    messages: 'Messages',
    user: 'User',
    userId: 'User ID',
    subject: 'Subject',
    confirm: 'Confirm',
    cancel: 'Cancel',
    previous: 'Previous',
    next: 'Next',
    pageOf: 'Page {page} of {totalPages} ({total} total)',
    allStatuses: 'All statuses',
    allPriorities: 'All priorities',
    noData: 'No data',
    conversations: 'Conversations',
    active: 'Active',
    inactive: 'Inactive',
  },
  dashboardPage: {
    subtitle: 'Overview of your Musaium platform.',
    stats: {
      totalUsers: 'Total Users',
      totalSessions: 'Total Sessions',
      totalMessages: 'Total Messages',
      recentSignups: 'New This Week',
      recentSessions: 'Recent Sessions',
    },
  },
  auditLogsPage: {
    subtitle: 'Review system audit logs.',
    filterPlaceholder: 'Filter by action...',
    columnUser: 'User',
    columnAction: 'Action',
    columnResource: 'Resource',
    columnDetails: 'Details',
    emptyState: 'No audit logs found.',
    tableAriaLabel: 'Audit logs table (scroll horizontally)',
  },
  usersPage: {
    subtitle: 'Manage platform users.',
    searchPlaceholder: 'Search...',
    allRoles: 'All roles',
    columnName: 'Name',
    columnRole: 'Role',
    columnStatus: 'Status',
    columnLastLogin: 'Last Login',
    emptyState: 'No users found.',
    changeRole: 'Change Role',
    view: 'View',
    viewAria: 'View user details',
  },
  userDetailPage: {
    subtitle: 'Detailed user view.',
    backToList: 'Back to users',
    loading: 'Loading user…',
    errorNotFound: 'User not found.',
    errorGeneric: 'Could not load this user.',
    errorLastAdmin: 'Cannot delete the last admin.',
    errorSelfAction: 'You cannot perform this action on your own account.',
    sectionIdentity: 'Identity',
    sectionStatus: 'Status',
    sectionLifecycle: 'Lifecycle',
    fieldId: 'ID',
    fieldEmail: 'Email',
    fieldName: 'Full name',
    fieldRole: 'Role',
    fieldMuseum: 'Museum',
    fieldVerified: 'Email verified',
    fieldSuspended: 'Suspended',
    fieldDeletedAt: 'Deleted at',
    fieldCreated: 'Created',
    fieldUpdated: 'Updated',
    badgeVerified: 'Verified',
    badgeUnverified: 'Unverified',
    badgeSuspended: 'Suspended',
    badgeActive: 'Active',
    badgeDeleted: 'Deleted',
    noValue: '—',
    actionsTitle: 'Actions',
    actionChangeRole: 'Change role',
    actionSuspend: 'Suspend',
    actionUnsuspend: 'Unsuspend',
    actionDelete: 'Delete',
    confirmSuspendTitle: 'Suspend this user?',
    confirmSuspendBody: '',
    confirmSuspendButton: 'Suspend',
    confirmUnsuspendTitle: 'Lift suspension?',
    confirmUnsuspendBody: '',
    confirmUnsuspendButton: 'Unsuspend',
    confirmDeleteTitle: 'Delete this user?',
    confirmDeleteBody: '',
    confirmDeleteTypeEmailLabel: 'Type email to confirm',
    confirmDeleteButton: 'Delete',
    successRoleChanged: 'Role updated.',
    successSuspended: 'User suspended.',
    successUnsuspended: 'User reactivated.',
    successDeleted: 'User deleted.',
    newRoleLabel: 'New role',
    tier: {
      label: 'Tier',
      currentFree: 'Free tier',
      currentPremium: 'Premium tier',
      toggleToPremium: 'Promote to premium',
      toggleToFree: 'Demote to free',
      confirmTitle: 'Change user tier?',
      confirmBody: 'Audit-logged change.',
      confirmCta: 'Confirm tier change',
      cancel: 'Cancel',
      success: 'Tier updated.',
      error: 'Could not update tier.',
    },
  },
  mfaPage: {
    successTitle: 'Two-factor authentication enabled',
    successBody: '',
    backToDashboard: 'Back to dashboard',
    setupTitle: 'Set up two-factor authentication',
    setupIntro: '',
    generateButton: 'Generate',
    generating: 'Generating…',
    qrAriaLabel: 'TOTP enrollment QR code',
    manualSecretIntro: '',
    recoveryTitle: 'Recovery codes',
    recoveryWarning: '',
    copyAll: 'Copy all',
    copyAllAria: 'Copy all recovery codes to clipboard',
    codeLabel: 'Enter the 6-digit code',
    codePlaceholder: '123456',
    verifyButton: 'Verify',
    verifying: 'Verifying…',
    errorPrefix: 'Error: ',
  },
  reportsPage: {
    subtitle: '',
    reason: 'Reason',
    message: 'Message',
    review: 'Review',
    reviewReport: 'Review Report',
    reportedMessage: 'Reported message',
    reviewerNotes: 'Notes',
    reviewerNotesPlaceholder: '',
    noReports: 'No reports',
  },
  ticketsPage: {
    subtitle: '',
    update: 'Update',
    view: 'View',
    updateTicket: 'Update Ticket',
    noTickets: 'No tickets',
  },
  reviewsPage: {
    subtitle: 'Manage visitor reviews and moderate content.',
    filterStatus: 'Filter by status',
    rating: 'Rating',
    comment: 'Comment',
    author: 'Author',
    approve: 'Approve',
    reject: 'Reject',
    confirmApprove: 'Approve this review?',
    confirmReject: 'Reject this review?',
    moderated: 'Moderated',
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    noReviews: 'No reviews found.',
  },
  supportPage: {
    subtitle: '',
    selectTicket: 'Select a ticket',
    viewTickets: 'View Tickets',
    backToTickets: 'Back',
    createdAt: 'Created',
    description: 'Description',
    noMessages: 'No messages',
    reply: 'Reply',
    replyPlaceholder: 'Type your reply...',
    send: 'Send',
    sending: 'Sending...',
  },
  analyticsPage: {
    subtitle: 'Monitor usage and engagement metrics.',
    avgMessages: 'Avg Messages',
    avgDuration: 'Avg Duration',
    returnRate: 'Return Rate',
    uniqueUsers: 'Unique Users',
    returningUsers: 'Returning Users',
    usage: 'Usage',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    days: 'Days',
    sessions: 'Sessions',
    messagesSent: 'Messages Sent',
    activeUsers: 'Active Users',
    topArtworks: 'Top Artworks',
    topMuseums: 'Top Museums',
    museum: 'Museum',
    guardrailBlockRate: 'Block Rate',
  },
  npsPage: {
    subtitle: 'Track visitor recommendation sentiment.',
    score: 'NPS score',
    promoters: 'Promoters',
    passives: 'Passives',
    detractors: 'Detractors',
    responses: 'Responses',
    distribution: 'Response distribution',
    chartAriaLabel: 'Bar chart of promoter, passive and detractor counts',
    allMuseums: 'All museums',
    noMuseumAssigned: 'No museum is assigned to your account. Please contact an administrator.',
  },
  export: {
    sessions: { label: 'CSV sessions', downloading: 'Preparing', error: 'Failed' },
    reviews: { label: 'CSV reviews', downloading: 'Preparing', error: 'Failed' },
    tickets: { label: 'CSV tickets', downloading: 'Preparing', error: 'Failed' },
  },
};
