/**
 * Shared factory for the smoke-account credentials used by the ephemeral
 * create→test→cleanup lifecycle specs (cycle C, run
 * 2026-05-26-auth-mfa-rgpd-zerodefect).
 *
 * DRY test discipline (CLAUDE.md § Test Discipline). The existing
 * `user.fixtures.ts` `makeUser()` builds a full `User` entity for unit-level
 * mocking; this helper instead produces the lightweight `{ email, password }`
 * credential pair the script's `create`/`cleanup` subcommands consume, plus a
 * unique-email helper so parallel integration cases never collide on the
 * `users.email` UNIQUE constraint.
 */

export interface SmokeCredentials {
  email: string;
  password: string;
}

/**
 * Deterministic-by-default smoke credentials. Pass `email` to scope a case to
 * its own row; the default password is a fixed, syntactically-valid value (the
 * REAL per-run password is generated by `createSmokeAccount` itself — this
 * fixture is only for pre-seeding residual rows / driving `cleanup`).
 */
export const makeSmokeCredentials = (
  overrides: Partial<SmokeCredentials> = {},
): SmokeCredentials => ({
  email: 'smoke+lifecycle@test.musaium',
  password: 'Sm0ke!Lifecycle-Test',
  ...overrides,
});

/**
 * Unique synthetic smoke email for a given case label, keeping the
 * `@test.musaium` domain marker so the rows are obviously synthetic.
 */
export const makeSmokeEmail = (label: string): string => `smoke+${label}@test.musaium`;
