services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dev-backend
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: dev-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - '5432:5432'
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: dev-adminer
    depends_on:
      - db
    ports:
      - '8080:8080'
    restart: unless-stopped

volumes:
  pgdata_dev:
