#!/usr/bin/env node
/**
 * Musaium Design System — Token Generator
 *
 * Reads canonical tokens from ./tokens/ and generates platform-specific files:
 *   - museum-frontend/shared/ui/tokens.generated.ts  (React Native)
 *   - museum-web/src/tokens.generated.css             (Tailwind 4 @theme)
 *
 * Usage: node --import tsx design-system/build.ts
 */

import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { colors } from './tokens/colors';
import { typography } from './tokens/typography';
import { spacing, radii } from './tokens/spacing';
import { functional } from './tokens/functional';
import { semantic } from './tokens/semantic';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

const HEADER = '/* AUTO-GENERATED by design-system/build.ts — DO NOT EDIT */';
const TS_HEADER = '// AUTO-GENERATED by design-system/build.ts — DO NOT EDIT';

// ─── Tailwind 4 CSS (@theme) ────────────────────────────────────────────────

function buildTailwindCSS(): string {
  const lines: string[] = [HEADER, '', '@theme {'];

  // Primary scale
  for (const [step, hex] of Object.entries(colors.primary)) {
    lines.push(`  --color-primary-${step}: ${hex};`);
  }
  lines.push('');

  // Accent scale
  for (const [step, hex] of Object.entries(colors.accent)) {
    lines.push(`  --color-accent-${step}: ${hex};`);
  }
  lines.push('');

  // Gold scale
  for (const [step, hex] of Object.entries(colors.gold)) {
    lines.push(`  --color-gold-${step}: ${hex};`);
  }
  lines.push('');

  // Semantic text
  for (const [name, hex] of Object.entries(colors.text)) {
    lines.push(`  --color-text-${name}: ${hex};`);
  }
  lines.push('');

  // Surfaces
  lines.push(`  --color-surface: ${colors.surface.default};`);
  lines.push(`  --color-surface-elevated: ${colors.surface.elevated};`);
  lines.push(`  --color-surface-muted: ${colors.surface.muted};`);
  lines.push('');

  // Typography
  lines.push(`  --font-sans: ${typography.fontFamily.sans};`);
  lines.push('');

  for (const [name, val] of Object.entries(typography.fontSize)) {
    lines.push(`  --font-size-${name}: ${val.rem};`);
  }
  lines.push('');

  for (const [name, val] of Object.entries(typography.fontWeight)) {
    lines.push(`  --font-weight-${name}: ${val.css};`);
  }
  lines.push('');

  for (const [name, val] of Object.entries(typography.lineHeight)) {
    lines.push(`  --line-height-${name}: ${val};`);
  }
  lines.push('');

  // Spacing
  for (const [name, val] of Object.entries(spacing)) {
    lines.push(`  --spacing-${name}: ${val.rem};`);
  }
  lines.push('');

  // Radii
  for (const [name, val] of Object.entries(radii)) {
    const suffix = name === 'DEFAULT' ? '' : `-${name}`;
    lines.push(`  --radius${suffix}: ${val.rem};`);
  }

  lines.push('}', '');
  return lines.join('\n');
}

// ─── React Native TS ────────────────────────────────────────────────────────

function buildReactNativeTS(): string {
  const lines: string[] = [TS_HEADER, ''];

  // Color scales as flat objects
  lines.push('export const primaryScale = {');
  for (const [step, hex] of Object.entries(colors.primary)) {
    lines.push(`  '${step}': '${hex}',`);
  }
  lines.push('} as const;', '');

  lines.push('export const accentScale = {');
  for (const [step, hex] of Object.entries(colors.accent)) {
    lines.push(`  '${step}': '${hex}',`);
  }
  lines.push('} as const;', '');

  lines.push('export const goldScale = {');
  for (const [step, hex] of Object.entries(colors.gold)) {
    lines.push(`  '${step}': '${hex}',`);
  }
  lines.push('} as const;', '');

  // Semantic text colors
  lines.push('export const textColors = {');
  for (const [name, hex] of Object.entries(colors.text)) {
    lines.push(`  ${name}: '${hex}',`);
  }
  lines.push('} as const;', '');

  lines.push('export const darkTextColors = {');
  for (const [name, hex] of Object.entries(colors.dark.text)) {
    lines.push(`  ${name}: '${hex}',`);
  }
  lines.push('} as const;', '');

  // Surfaces
  lines.push('export const surfaceColors = {');
  for (const [name, hex] of Object.entries(colors.surface)) {
    lines.push(`  ${name}: '${hex}',`);
  }
  lines.push('} as const;', '');

  lines.push('export const darkSurfaceColors = {');
  for (const [name, hex] of Object.entries(colors.dark.surface)) {
    lines.push(`  ${name}: '${hex}',`);
  }
  lines.push('} as const;', '');

  // Status colors
  lines.push('export const statusColors = {');
  for (const [name, val] of Object.entries(colors.status)) {
    lines.push(`  ${name}: { light: '${val.light}', dark: '${val.dark}' },`);
  }
  lines.push('} as const;', '');

  // Typography — px values for React Native
  lines.push('export const fontSize = {');
  for (const [name, val] of Object.entries(typography.fontSize)) {
    const key = /^\d/.test(name) ? `'${name}'` : name;
    lines.push(`  ${key}: ${val.px},`);
  }
  lines.push('} as const;', '');

  lines.push('export const fontWeight = {');
  for (const [name, val] of Object.entries(typography.fontWeight)) {
    const key = /^\d/.test(name) ? `'${name}'` : name;
    lines.push(`  ${key}: '${val.css}',`);
  }
  lines.push('} as const;', '');

  lines.push('export const lineHeight = {');
  for (const [name, val] of Object.entries(typography.lineHeight)) {
    lines.push(`  ${name}: ${val},`);
  }
  lines.push('} as const;', '');

  // Spacing — px values for React Native
  lines.push('export const space = {');
  for (const [name, val] of Object.entries(spacing)) {
    const key = /^\d/.test(name) || name.includes('.') ? `'${name}'` : name;
    lines.push(`  ${key}: ${val.px},`);
  }
  lines.push('} as const;', '');

  // Radii — px values for React Native
  lines.push('export const radius = {');
  for (const [name, val] of Object.entries(radii)) {
    const key = /^\d/.test(name) ? `'${name}'` : name;
    lines.push(`  ${key}: ${val.px},`);
  }
  lines.push('} as const;', '');

  // Gradient colors
  if (colors.gradient) {
    lines.push('export const gradientColors = {');
    for (const [name, hex] of Object.entries(colors.gradient)) {
      lines.push(`  ${name}: '${hex}',`);
    }
    lines.push('} as const;', '');
  }

  return lines.join('\n');
}

// ─── React Native: Functional tokens ────────────────────────────────────────

function buildReactNativeFunctional(): string {
  const lines: string[] = [TS_HEADER, ''];

  lines.push('/**');
  lines.push(' * Converts a hex color to rgba with the given alpha.');
  lines.push(' * Works with 3-char (#fff), 6-char (#ffffff), and 8-char (#ffffffaa) hex.');
  lines.push(' */');
  lines.push('export function withOpacity(hex: string, alpha: number): string {');
  lines.push("  const clean = hex.replace('#', '');");
  lines.push('  let r: number, g: number, b: number;');
  lines.push('  if (clean.length === 3) {');
  lines.push('    r = parseInt(clean[0] + clean[0], 16);');
  lines.push('    g = parseInt(clean[1] + clean[1], 16);');
  lines.push('    b = parseInt(clean[2] + clean[2], 16);');
  lines.push('  } else {');
  lines.push('    r = parseInt(clean.slice(0, 2), 16);');
  lines.push('    g = parseInt(clean.slice(2, 4), 16);');
  lines.push('    b = parseInt(clean.slice(4, 6), 16);');
  lines.push('  }');
  lines.push('  return `rgba(${r}, ${g}, ${b}, ${alpha})`;');
  lines.push('}');
  lines.push('');

  lines.push('export const functional = {');
  for (const [key, val] of Object.entries(functional)) {
    lines.push(`  ${key}: '${val}',`);
  }
  lines.push('} as const;');
  lines.push('');

  return lines.join('\n');
}

// ─── React Native: Semantic tokens ──────────────────────────────────────────

function buildReactNativeSemantic(): string {
  const lines: string[] = [TS_HEADER, ''];

  function writeEntries(obj: Record<string, unknown>, depth: number): void {
    const indent = '  '.repeat(depth);
    for (const [key, val] of Object.entries(obj)) {
      if (typeof val === 'object' && val !== null && !Array.isArray(val)) {
        lines.push(`${indent}${key}: {`);
        writeEntries(val as Record<string, unknown>, depth + 1);
        lines.push(`${indent}},`);
      } else if (typeof val === 'string') {
        lines.push(`${indent}${key}: '${val}',`);
      } else {
        lines.push(`${indent}${key}: ${String(val)},`);
      }
    }
  }

  lines.push('export const semantic = {');
  for (const [category, tokens] of Object.entries(semantic)) {
    lines.push(`  ${category}: {`);
    writeEntries(tokens as Record<string, unknown>, 2);
    lines.push('  },');
  }
  lines.push('} as const;');
  lines.push('');

  return lines.join('\n');
}

// ─── Web CSS: Functional tokens ─────────────────────────────────────────────

function buildFunctionalCSS(): string {
  const lines: string[] = [HEADER, '', '@theme {'];

  for (const [key, val] of Object.entries(functional)) {
    const cssKey = key.replace(/([A-Z])/g, '-$1').toLowerCase();
    lines.push(`  --fn-${cssKey}: ${val};`);
  }

  lines.push('}', '');
  return lines.join('\n');
}

// ─── Web CSS: Semantic tokens ───────────────────────────────────────────────

function buildSemanticCSS(): string {
  const lines: string[] = [HEADER, '', '@theme {'];

  for (const [category, tokens] of Object.entries(semantic)) {
    lines.push(`  /* ${category} */`);
    for (const [key, val] of Object.entries(tokens as Record<string, unknown>)) {
      if (typeof val === 'object' && val !== null) {
        for (const [subKey, subVal] of Object.entries(val as Record<string, unknown>)) {
          if (typeof subVal === 'string') {
            const cssKey = `--sem-${category}-${key}-${subKey}`.replace(/([A-Z])/g, '-$1').toLowerCase();
            lines.push(`  ${cssKey}: ${subVal};`);
          }
        }
      } else if (typeof val === 'number') {
        const cssKey = `--sem-${category}-${key}`.replace(/([A-Z])/g, '-$1').toLowerCase();
        const remVal = val === 0 ? '0' : `${val / 16}rem`;
        lines.push(`  ${cssKey}: ${remVal};`);
      } else if (typeof val === 'string') {
        const cssKey = `--sem-${category}-${key}`.replace(/([A-Z])/g, '-$1').toLowerCase();
        lines.push(`  ${cssKey}: ${val};`);
      }
    }
    lines.push('');
  }

  lines.push('}', '');
  return lines.join('\n');
}

// ─── Write outputs ──────────────────────────────────────────────────────────

const outputs = [
  {
    path: resolve(root, 'museum-frontend/shared/ui/tokens.generated.ts'),
    content: buildReactNativeTS(),
    label: 'museum-frontend (primitives)',
  },
  {
    path: resolve(root, 'museum-frontend/shared/ui/tokens.functional.ts'),
    content: buildReactNativeFunctional(),
    label: 'museum-frontend (functional)',
  },
  {
    path: resolve(root, 'museum-frontend/shared/ui/tokens.semantic.ts'),
    content: buildReactNativeSemantic(),
    label: 'museum-frontend (semantic)',
  },
  {
    path: resolve(root, 'museum-web/src/tokens.generated.css'),
    content: buildTailwindCSS(),
    label: 'museum-web (primitives)',
  },
  {
    path: resolve(root, 'museum-web/src/tokens.functional.css'),
    content: buildFunctionalCSS(),
    label: 'museum-web (functional)',
  },
  {
    path: resolve(root, 'museum-web/src/tokens.semantic.css'),
    content: buildSemanticCSS(),
    label: 'museum-web (semantic)',
  },
];

for (const { path, content, label } of outputs) {
  writeFileSync(path, content, 'utf-8');
  console.log(`  ✓ ${label} → ${path.replace(root + '/', '')}`);
}

console.log(`\n  Done — ${outputs.length} files generated from design-system/tokens/`);
