#!/usr/bin/env node
/**
 * Musaium Design System — Token Generator
 *
 * Reads canonical tokens from ./tokens/ and generates platform-specific files:
 *   - museum-frontend/shared/ui/tokens.generated.ts  (React Native)
 *   - museum-web/src/tokens.generated.css             (Tailwind 4 @theme)
 *   - museum-admin/src/tokens.generated.css            (Tailwind 4 @theme)
 *
 * Usage: node --import tsx design-system/build.ts
 */

import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { colors } from './tokens/colors';
import { typography } from './tokens/typography';
import { spacing, radii } from './tokens/spacing';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

const HEADER = '/* AUTO-GENERATED by design-system/build.ts — DO NOT EDIT */';
const TS_HEADER = '// AUTO-GENERATED by design-system/build.ts — DO NOT EDIT';

// ─── Tailwind 4 CSS (@theme) ────────────────────────────────────────────────

function buildTailwindCSS(): string {
  const lines: string[] = [HEADER, '', '@theme {'];

  // Primary scale
  for (const [step, hex] of Object.entries(colors.primary)) {
    lines.push(`  --color-primary-${step}: ${hex};`);
  }
  lines.push('');

  // Accent scale
  for (const [step, hex] of Object.entries(colors.accent)) {
    lines.push(`  --color-accent-${step}: ${hex};`);
  }
  lines.push('');

  // Gold scale
  for (const [step, hex] of Object.entries(colors.gold)) {
    lines.push(`  --color-gold-${step}: ${hex};`);
  }
  lines.push('');

  // Semantic text
  for (const [name, hex] of Object.entries(colors.text)) {
    lines.push(`  --color-text-${name}: ${hex};`);
  }
  lines.push('');

  // Surfaces
  lines.push(`  --color-surface: ${colors.surface.default};`);
  lines.push(`  --color-surface-elevated: ${colors.surface.elevated};`);
  lines.push(`  --color-surface-muted: ${colors.surface.muted};`);
  lines.push('');

  // Typography
  lines.push(`  --font-sans: ${typography.fontFamily.sans};`);
  lines.push('');

  for (const [name, val] of Object.entries(typography.fontSize)) {
    lines.push(`  --font-size-${name}: ${val.rem};`);
  }
  lines.push('');

  for (const [name, val] of Object.entries(typography.fontWeight)) {
    lines.push(`  --font-weight-${name}: ${val.css};`);
  }
  lines.push('');

  for (const [name, val] of Object.entries(typography.lineHeight)) {
    lines.push(`  --line-height-${name}: ${val};`);
  }
  lines.push('');

  // Spacing
  for (const [name, val] of Object.entries(spacing)) {
    lines.push(`  --spacing-${name}: ${val.rem};`);
  }
  lines.push('');

  // Radii
  for (const [name, val] of Object.entries(radii)) {
    const suffix = name === 'DEFAULT' ? '' : `-${name}`;
    lines.push(`  --radius${suffix}: ${val.rem};`);
  }

  lines.push('}', '');
  return lines.join('\n');
}

// ─── React Native TS ────────────────────────────────────────────────────────

function buildReactNativeTS(): string {
  const lines: string[] = [TS_HEADER, ''];

  // Color scales as flat objects
  lines.push('export const primaryScale = {');
  for (const [step, hex] of Object.entries(colors.primary)) {
    lines.push(`  '${step}': '${hex}',`);
  }
  lines.push('} as const;', '');

  lines.push('export const accentScale = {');
  for (const [step, hex] of Object.entries(colors.accent)) {
    lines.push(`  '${step}': '${hex}',`);
  }
  lines.push('} as const;', '');

  lines.push('export const goldScale = {');
  for (const [step, hex] of Object.entries(colors.gold)) {
    lines.push(`  '${step}': '${hex}',`);
  }
  lines.push('} as const;', '');

  // Semantic text colors
  lines.push('export const textColors = {');
  for (const [name, hex] of Object.entries(colors.text)) {
    lines.push(`  ${name}: '${hex}',`);
  }
  lines.push('} as const;', '');

  lines.push('export const darkTextColors = {');
  for (const [name, hex] of Object.entries(colors.dark.text)) {
    lines.push(`  ${name}: '${hex}',`);
  }
  lines.push('} as const;', '');

  // Surfaces
  lines.push('export const surfaceColors = {');
  for (const [name, hex] of Object.entries(colors.surface)) {
    lines.push(`  ${name}: '${hex}',`);
  }
  lines.push('} as const;', '');

  lines.push('export const darkSurfaceColors = {');
  for (const [name, hex] of Object.entries(colors.dark.surface)) {
    lines.push(`  ${name}: '${hex}',`);
  }
  lines.push('} as const;', '');

  // Status colors
  lines.push('export const statusColors = {');
  for (const [name, val] of Object.entries(colors.status)) {
    lines.push(`  ${name}: { light: '${val.light}', dark: '${val.dark}' },`);
  }
  lines.push('} as const;', '');

  // Typography — px values for React Native
  lines.push('export const fontSize = {');
  for (const [name, val] of Object.entries(typography.fontSize)) {
    const key = /^\d/.test(name) ? `'${name}'` : name;
    lines.push(`  ${key}: ${val.px},`);
  }
  lines.push('} as const;', '');

  lines.push('export const fontWeight = {');
  for (const [name, val] of Object.entries(typography.fontWeight)) {
    const key = /^\d/.test(name) ? `'${name}'` : name;
    lines.push(`  ${key}: '${val.css}',`);
  }
  lines.push('} as const;', '');

  lines.push('export const lineHeight = {');
  for (const [name, val] of Object.entries(typography.lineHeight)) {
    lines.push(`  ${name}: ${val},`);
  }
  lines.push('} as const;', '');

  // Spacing — px values for React Native
  lines.push('export const space = {');
  for (const [name, val] of Object.entries(spacing)) {
    const key = /^\d/.test(name) || name.includes('.') ? `'${name}'` : name;
    lines.push(`  ${key}: ${val.px},`);
  }
  lines.push('} as const;', '');

  // Radii — px values for React Native
  lines.push('export const radius = {');
  for (const [name, val] of Object.entries(radii)) {
    const key = /^\d/.test(name) ? `'${name}'` : name;
    lines.push(`  ${key}: ${val.px},`);
  }
  lines.push('} as const;', '');

  // Gradient colors
  if (colors.gradient) {
    lines.push('export const gradientColors = {');
    for (const [name, hex] of Object.entries(colors.gradient)) {
      lines.push(`  ${name}: '${hex}',`);
    }
    lines.push('} as const;', '');
  }

  return lines.join('\n');
}

// ─── Write outputs ──────────────────────────────────────────────────────────

const outputs = [
  {
    path: resolve(root, 'museum-frontend/shared/ui/tokens.generated.ts'),
    content: buildReactNativeTS(),
    label: 'museum-frontend',
  },
  {
    path: resolve(root, 'museum-web/src/tokens.generated.css'),
    content: buildTailwindCSS(),
    label: 'museum-web',
  },
  {
    path: resolve(root, 'museum-admin/src/tokens.generated.css'),
    content: buildTailwindCSS(),
    label: 'museum-admin',
  },
];

for (const { path, content, label } of outputs) {
  writeFileSync(path, content, 'utf-8');
  console.log(`  ✓ ${label} → ${path.replace(root + '/', '')}`);
}

console.log(`\n  Done — ${outputs.length} files generated from design-system/tokens/`);
